### ISSUE TITLE
Could not parse aggregated battery stats.

### ISSUE THREAD

**Issue by leowang22** [google/battery-historian#55]
_Please_ wait, drawing chart...
Error generating historian plot: failed to run command "python scripts/historian.py -c -m -r bugreport_1458786580296.log /tmp/historian973499639": exit status 1 Traceback (most recent call last): File "scripts/historian.py", line 1598, in main() File "scripts/historian.py", line 1347, in main time_delta_s = parse_time(line_time, fmt) + time_offset File "scripts/historian.py", line 107, in parse_time d = match.groupdict() AttributeError: 'NoneType' object has no attribute 'groupdict'

**Comment by parkerlreed** [comment]
I'm getting this when trying to analyze a bug report from 7.1.1 using the official hosted version.

**Comment by simowce** [comment]
I met this problem when using Android 7.1.1, too.

**Comment by parkerlreed** [comment]
@simowce I think this was fixed. I've been using a locally hosted version (the go package) without any issues.

**Comment by arjitsrivastava** [comment]
I'm getting the same error on the official hosted version still. Was anyone able to resolve this? Does the Historian tab work on Android 21 and below? And Historian v2 works works on everything else?
