### ISSUE TITLE
Error when run battery-historian.go

### ISSUE THREAD

**Issue by IbnRamli** [google/battery-historian#74]
Need help from anyone.
When I run battery-historian.go, it said :

panic: open templates/base.html: The system cannot find the path specified.

goroutine 1 [running]:
panic(0x81fec0, 0x10de30c0)
        C:/Go/src/runtime/panic.go:481 +0x326
html/template.Must(0x0, 0x2b4bb8, 0x10de30c0, 0x0)
        C:/Go/src/html/template/template.go:340 +0x44
github.com/google/battery-historian/analyzer.InitTemplates(0x8b0e90, 0xb)
        C:/work/code/go/src/github.com/google/battery-historian/analyzer/analyze
r.go:319 +0x179
main.main()
        C:/work/code/go/src/github.com/google/battery-historian/cmd/battery-hist
orian/battery-historian.go:70 +0x3b
exit status 2

What its mean?
Did I miss something?

**Comment by ajthemacboy** [comment]
Getting this as well. I have to re-build every time I want to start.

**Comment by ishan-dhingra** [comment]
Had the same problem, below fix did the trick:

Make sure you are running command from directory where source code of battery-historian is placed:

`eg: mine is: ~/GoWorkSpace/src/github.com/google/battery-historian`

being in above-mentioned directory I am executing as follow:

`go run cmd/battery-historian/battery-historian.go`

**Comment by AlbertHdz4** [comment]
I know this is very old but I had the same issue, as  @ishan-dhingra said, make sure that you are running from the source code, if not enter command:

`cd ~/go/src/github.com/google/battery-historian`

and then: 

 `go run cmd/battery-historian/battery-historian.go [--port default:9999]`

Hope this can be useful

**Comment by tysj78** [comment]
> I know this is very old but I had the same issue, as @ishan-dhingra said, make sure that you are running from the source code, if not enter command:
> 
> `cd ~/go/src/github.com/google/battery-historian`
> 
> and then:
> 
> `go run cmd/battery-historian/battery-historian.go [--port default:9999]`
> 
> Hope this can be useful

Solved my problem
